version: '3.8'
services:
  db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: agemed
    networks:
      - agemed-net
      
  # api:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   command: npm run dev
  #   ports:
  #     - 3333:3333
  #   depends_on:
  #     - db
  #   environment:
  #     - DATABASE_URL="postgresql://postgres:root@localhost:5434/agemed?schema=public"

networks:
  agemed-net:
