/ userController.js

const prisma = require('@prisma/client');

async function getUsers() {
    return await prisma.user.findMany();
}

module.exports = { getUsers };
javascript
Copiar código
// userController.test.js

const { getUsers } = require('./userController');

jest.mock('@prisma/client', () => ({
    __esModule: true,
    user: {
        findMany: jest.fn().mockResolvedValue([
            { id: 1, name: 'User 1' },
            { id: 2, name: 'User 2' }
        ])
    }
}));

describe('getUsers', () => {
    it('should return list of users', async () => {
        const users = await getUsers();
        expect(users).toHaveLength(2);
        expect(users[0].name).toBe('User 1');
        expect(users[1].name).toBe('User 2');
    });
});
