const { add } = require('./code');


test('add function adds two numbers correctly', () => {
  expect(add(1, 2)).toBe(3);
  expect(add(-1, 1)).toBe(0);
  expect(add(0, 0)).toBe(0);
});


test('add function works correctly with decimal numbers', () => {
  expect(add(1.5, 2.5)).toBe(4);
  expect(add(-1.5, 1.5)).toBe(0);
  expect(add(0.1, 0.2)).toBeCloseTo(0.3);
});


test('add function throws an error with invalid arguments', () => {
  expect(() => add('1', 2)).toThrow();
  expect(() => add(1, '2')).toThrow();
  expect(() => add(null, 2)).toThrow();
  expect(() => add(1, undefined)).toThrow();
});
